# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nove

pool: edfstage

steps:
- script: |
    #!/bin/bash
    echo "Current user on the agent machine: $(whoami)"
  displayName: 'Check Current User'

- script: |
    #!/bin/bash
    
    # Remove existing Python installations
    sudo apt-get remove --purge -qq -y python3 python3-pip python3-setuptools virtualenv pytest pytest-cov pytest-azurepipelines mypy
    
    # Optionally, remove Python alternatives if needed
    # sudo update-alternatives --remove python /usr/bin/python3.8
    
    green='\033[0;32m'; clear='\033[0m'
    printf "${green}Removed existing Python installations${clear}"
  displayName: 'Remove Existing Python'

- script: |
    #!/bin/bash
    # shellcheck disable=SC2086,SC2059,SC1073,SC1072 # skip checks before scripts are complete
    
    # PIP3 Managed packages
    # Update the installed version (installed from Python39)
    # Install or Update required Python Packages
    #
    # https://pypi.org/project/setuptools/
    # https://virtualenv.pypa.io/en/latest/installation.html
    
    export DEBIAN_FRONTEND=noninteractive
    echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
    
    #--------------------------------------------------------------
    # Pip installs for python 3.8
    #--------------------------------------------------------------
    
    sudo update-alternatives --set python /usr/bin/python3.8
    sudo chown -R moedf /usr/local
    
    pip3 install -U --ignore-installed --no-input --no-cache-dir \
        setuptools \
        virtualenv \
        pytest \
        pytest-cov \
        pytest-azurepipelines \
        mypy || exit 99
    
    #--------------------------------------------------------------
    # Pip for python 3.9
    #--------------------------------------------------------------
    
    sudo update-alternatives --set python /usr/bin/python3.9
    sudo chown -R moedf /usr/local
    
    pip3 install -U --ignore-installed --no-input --no-cache-dir \
        setuptools \
        virtualenv \
        pytest \
        pytest-cov \
        pytest-azurepipelines \
        mypy || exit 99
    
    green='\033[0;32m'; clear='\033[0m'
    
    printf "${green} installed $(which pip3) $(pip3 --version) ${clear}
            ${green} installed $(which virtualenv) $(virtualenv --version) ${clear}
            ${green} installed $(which pytest) $(pytest --version) ${clear}
            ${green} installed $(which mypy) $(mypy --version) ${clear}"
  displayName: 'Install Python Packages'

- script: |
    #!/bin/bash
    
    # Install Checkov using pip with full path
    pip3 install --ignore-installed --no-input --upgrade --no-cache-dir checkov || exit 99
    sudo chmod +x /usr/local/bin/checkov
    
    # Check Checkov version
    checkov_version=$(checkov --version 2>&1)
    green='\033[0;32m'; clear='\033[0m'
    
    printf "${green}Installed Checkov ${checkov_version} ${clear}"
  displayName: 'Install Checkov and Check Version'
